general:
  name: "Blokky"
  summary: "Blokky - Stop doomscrolling"
  description: "Blocky is a simple app that blocks Reels / Shorts. You can still use those apps as usual, but you won't be disturbed by Reels / Shorts anymore."
  url: "https://blokky.robingebert.com"
  logo_image: "/src/site/img/logo.png"
  #logo_icon: lucide-lab:chest
  color: 
    light: "#FF5722"
    dark: "#E64A19"
  version: "1.0.1"
  device: "smartphone" # "smartphone" | "desktop" | "browser"

store:
  play_store: "https://play.google.com/store/apps/details?id=com.robingebert.blokky"

features:
  - title: "Easy usage"
    description: "Few clicks and you will not be disturbed by Reels anymore"
    icon: "material-symbols:edit-square-outline-rounded"

  - title: "Open source"
    description: "No hidden code, everything is open source. You can check it out on GitHub"
    icon: "material-symbols:rocket-launch-rounded"
    link: "https://github.com/Ronjar/Blokky"
  
  - title: "Designed with Privacy in mind"
    description: "No data is collected, no ads are shown. Just a simple app to block Reels"
    icon: "material-symbols:security-rounded"
    link: "/sites/AboutAccessibilityServices"